language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: FjfhWandBSsNKaUobQb2LQBWMwiqe+R9AlZdlOaWGoMIbDXtDU28eGRrah/TN3yvcYM4YZ6zVH8pqHBZEhT/qZGkICMTOw6CzTDkbLDpc/rc4+EL2v18yFVuPKXgLCpH1QSfztXStmdvrCdu7qDMYVIj8fn1ThtlvIseTiEy7DDujSCTlTfHtqP68fH7Cy3WqVMfssl1pJEGk7EZNo+c7gU/aVu7x4v/auDwbCUomwrORiKVfRZHm42vZ83ItO5avpqwZrYaURJQywSQtAbL7Ku5ZH3emteWSMghRkQGab+8zTI5zl/pKJsasDQ+ZaAyoheVrkm89UKmXSxIN/vh7BPLrZG1zgk9CXQvmwbbctjXQtfPwEH4ljplD7ZRFCAxK2xbhyQr5/cOf+nZk0EpjSX8alz6+H5MugQcG0L1n0/gkQU9IUr+Hz9JX+o67YKRVPue1acqdxpogb7REwKpcvKTu9QpJb0uoWCECG9tr/U5Fy8Tl0mhn472gulFu0kwYaE9uUOFFx0TFNF8WsRyERw9FTU2BYXEKVXeCaBEJyaPxtuwL8FJMzQIR1pdejTvqpqntnHIPIenqCYQ6UEq2XbdMBQyZkY65AFNhakbAghUecsDNzxwm1SNrZJlSLQ/WN+3yP4InVZWB9ig1heQouMvIsP42jFdmH6Fk1IeLmY=
before_install:
- openssl aes-256-cbc -K $encrypted_9eda98f28cb3_key -iv $encrypted_9eda98f28cb3_iv
  -in key.snk.enc -out key.snk -d
